In [1]:
import numpy as np
np.random.seed(1234)  # This makes sure that random is not random...

# Indexing, Slicing, etc

In [3]:
# Let's create a 7x7 array
s_by_s = np.arange(49).reshape((7,7))
print(s_by_s)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]


In [7]:
# Write Code to extract ...
# rows starting with [14 ...] and [21 ...]
s_by_s[2:4]
# every second columns starting from 2

array([[14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [9]:
# every second columns starting from 2
s_by_s[:, 1::2]

array([[ 1,  3,  5],
       [ 8, 10, 12],
       [15, 17, 19],
       [22, 24, 26],
       [29, 31, 33],
       [36, 38, 40],
       [43, 45, 47]])

# Functions in Numpy

In [10]:
# construct a 2D  array
twenty_ints = np.linspace(0,95, 20, dtype=np.int8)
twoD_arr = twenty_ints.reshape(4, -1)
print(twoD_arr)

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]


In [11]:
print(twoD_arr.mean())  # mean of all

47.5


In [12]:
print(twoD_arr.mean(axis=0))  # means of columns

[37.5 42.5 47.5 52.5 57.5]


In [13]:
print(twoD_arr.mean(axis=1))  # means of rows

[10. 35. 60. 85.]


# Filters...

In [14]:
filter = twoD_arr < 50
print(filter)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]
 [False False False False False]]


In [30]:
# Update where filtered:
# filtered_values = twoD_arr[filter]
# print(filtered_values)

filtered_array = np.where(filter, twoD_arr, 0)
print(filtered_array)

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


# Combine the two

In [2]:
np.random.seed(12345)
practice = np.random.rand(4, 5)
practice

array([[0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503],
       [0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987],
       [0.74771481, 0.96130674, 0.0083883 , 0.10644438, 0.29870371],
       [0.65641118, 0.80981255, 0.87217591, 0.9646476 , 0.72368535]])

In [4]:
# Calculate the column-wise **sum** of every second column
print(practice[:, 1::2].sum(axis=0))

[3.05200936 2.02455889]


In [5]:
# Compute the minimum of every row
print(practice.min(axis=1))

[0.18391881 0.5955447  0.0083883  0.65641118]


In [7]:
# Compute the absolute minimum
print(np.abs(practice).min())

0.00838829794155349


In [9]:
# Set the cells that are larger than 0.8 to 1
filter = practice > 0.8
practice[filter] = 1
print(practice)

[[1.         0.31637555 0.18391881 0.20456028 0.56772503]
 [0.5955447  1.         0.6531771  0.74890664 0.65356987]
 [0.74771481 1.         0.0083883  0.10644438 0.29870371]
 [0.65641118 1.         1.         1.         0.72368535]]


In [10]:
# Task 3
student_scores = np.random.randint(0,11,(10, 5))
student_scores

array([[ 7,  4,  0,  3,  5],
       [ 7,  3,  1,  5,  2],
       [ 5,  3,  8,  5,  2],
       [ 5,  3,  0,  6,  8],
       [ 0,  5, 10,  6,  8],
       [ 9,  2,  2,  2,  9],
       [10,  7,  5,  7,  1],
       [ 0, 10,  9, 10,  3],
       [ 0,  3,  0,  6,  2],
       [ 1,  5,  8,  6,  5]], dtype=int32)

In [12]:
# For each student (row)
for row in student_scores:
    print(f"Min: {min(row)}")
    print(f"Max: {max(row)}")
    print(f"Mean: {np.mean(row)}")
    print(f"StdDev: {np.std(row)}")
    print()

Min: 0
Max: 7
Mean: 3.8
StdDev: 2.3151673805580453

Min: 1
Max: 7
Mean: 3.6
StdDev: 2.154065922853802

Min: 2
Max: 8
Mean: 4.6
StdDev: 2.0591260281974

Min: 0
Max: 8
Mean: 4.4
StdDev: 2.727636339397171

Min: 0
Max: 10
Mean: 5.8
StdDev: 3.3704599092705436

Min: 2
Max: 9
Mean: 4.8
StdDev: 3.4292856398964493

Min: 1
Max: 10
Mean: 6.0
StdDev: 2.9664793948382653

Min: 0
Max: 10
Mean: 6.4
StdDev: 4.127953488110059

Min: 0
Max: 6
Mean: 2.2
StdDev: 2.2271057451320084

Min: 1
Max: 8
Mean: 5.0
StdDev: 2.280350850198276



In [16]:
# For each assignment (column)
for col in student_scores.T: # Use transpose to access them
    print(f"Min: {min(col)}")
    print(f"Max: {max(col)}")
    print(f"Mean: {np.mean(col)}")
    print(f"StdDev: {np.std(col)}")
    print()

Min: 0
Max: 10
Mean: 4.4
StdDev: 3.693237062523877

Min: 2
Max: 10
Mean: 4.5
StdDev: 2.29128784747792

Min: 0
Max: 10
Mean: 4.3
StdDev: 3.925557285278104

Min: 2
Max: 10
Mean: 5.6
StdDev: 2.0591260281974

Min: 1
Max: 9
Mean: 4.5
StdDev: 2.80178514522438



In [17]:
# Treat the entire array as one collection of numbers
combined_scores = student_scores.flatten()

print(f"Min: {np.min(combined_scores)}")
print(f"Max: {np.max(combined_scores)}")
print(f"Mean: {np.mean(combined_scores)}")
print(f"StdDev: {np.std(combined_scores)}")


Min: 0
Max: 10
Mean: 4.66
StdDev: 3.0829206931090525


In [20]:
min_ = 10
max_ = 0
mean_list = []
std_dev_list = []

for row in student_scores:
    if min(row) < min_:
        min_ = min(row)
        
    if max(row) > max_:
        max_ = max(row)
        
    mean_list.append(np.mean(row))
    
for col in student_scores.T: 
    if min(col) < min_:
        min_ = min(col)
        
    if max(col) > max_:
        max_ = max(col)
        
    mean_list.append(np.mean(col))

# To get the correct standard deviation, apply np.std() to the entire flattened array
combined_scores = student_scores.flatten()

print(f"Min: {min_}")
print(f"Max: {max_}")
print(f"Mean: {np.mean(mean_list)}")  # This is fine as you're averaging means
print(f"StdDev: {np.std(combined_scores)}")  # Standard deviation of all scores combined

Min: 0
Max: 10
Mean: 4.659999999999999
StdDev: 3.0829206931090525


In [21]:
for i, col in enumerate(student_scores.T):  # Transpose to iterate over columns (assignments)
    q1 = np.percentile(col, 25)  # 25th percentile
    q2 = np.percentile(col, 50)  # 50th percentile (median)
    q3 = np.percentile(col, 75)  # 75th percentile
    
    print(f"Assignment {i+1}:")
    print(f"  25th percentile (Q1): {q1}")
    print(f"  50th percentile (Median, Q2): {q2}")
    print(f"  75th percentile (Q3): {q3}")
    print()


Assignment 1:
  25th percentile (Q1): 0.25
  50th percentile (Median, Q2): 5.0
  75th percentile (Q3): 7.0

Assignment 2:
  25th percentile (Q1): 3.0
  50th percentile (Median, Q2): 3.5
  75th percentile (Q3): 5.0

Assignment 3:
  25th percentile (Q1): 0.25
  50th percentile (Median, Q2): 3.5
  75th percentile (Q3): 8.0

Assignment 4:
  25th percentile (Q1): 5.0
  50th percentile (Median, Q2): 6.0
  75th percentile (Q3): 6.0

Assignment 5:
  25th percentile (Q1): 2.0
  50th percentile (Median, Q2): 4.0
  75th percentile (Q3): 7.25

